package:
  name: template_experiment
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  - git_url: ../
  - git_url: https://github.com/fynnbe/template_experiment_models
    git_ref: HEAD

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '_') }}
  script: python setup.py install

requirements:
  run:
    - python=3.7.2
    - pytorch=1.1.0

tests:
  imports:
    - template_experiment
    - template_experiment_models
