{% set data = load_setup_py_data() %}

package:
  name: example_project
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ..
#  git_url: https://github.com/fynnbe/template_experiment

#  path: ..
#  - git_url: https://github.com/fynnbe/template_experiment_models
#    git_ref: HEAD
#    folder: template_experiments_models

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python=3.7.2
    - pip
  run:
    - python=3.7.2
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - template_experiment
    - template_experiment_models
